# Generated by Django 4.2.7 on 2026-06-04 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('food', 'Food & Dining'), ('transport', 'Transport'), ('shopping', 'Shopping'), ('bills', 'Bills & Utilities'), ('health', 'Health & Medical'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(choices=[('salary', 'Salary'), ('freelance', 'Freelance'), ('business', 'Business'), ('investment', 'Investment'), ('gift', 'Gift'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'income',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
